In [2]:
import pandas as pd
import sklearn
import matplotlib.pyplot as plt

## Race

In [3]:
race = pd.read_excel('Table1_v2.xls', sheet_name=6)

race

,Race,Incidents,Offenses,Victims1,Known\noffenders2
0,Anti-White,666,755,775,645
1,Anti-Black or African American,1930,2314,2391,1682
2,Anti-American Indian or Alaska Native,119,126,135,101
3,Anti-Asian,158,205,215,153
4,Anti-Native Hawaiian or Other Pacific Islander,21,25,26,26
5,"Anti-Multiple Races, Group",134,171,173,82
6,Anti-Arab,95,122,126,86
7,Anti-Hispanic or Latino,527,676,693,547
8,Anti-Other Race/Ethnicity/Ancestry,313,390,396,228
9,Total,3963,4784,4930,3550
10,Single Bias Incidents,7103,8302,8552,6268

In [4]:
race.columns

Index(['Race', 'Incidents', 'Offenses', 'Victims1', 'Known\noffenders2'], dtype='object')

In [5]:
# Reassign column names

race.rename(columns={'Victims1':'Victims', 'Known\noffenders2':'Known_Offenders'}, inplace=True)

race.columns

Index(['Race', 'Incidents', 'Offenses', 'Victims', 'Known_Offenders'], dtype='object')

In [6]:
race

,Race,Incidents,Offenses,Victims,Known_Offenders
0,Anti-White,666,755,775,645
1,Anti-Black or African American,1930,2314,2391,1682
2,Anti-American Indian or Alaska Native,119,126,135,101
3,Anti-Asian,158,205,215,153
4,Anti-Native Hawaiian or Other Pacific Islander,21,25,26,26
5,"Anti-Multiple Races, Group",134,171,173,82
6,Anti-Arab,95,122,126,86
7,Anti-Hispanic or Latino,527,676,693,547
8,Anti-Other Race/Ethnicity/Ancestry,313,390,396,228
9,Total,3963,4784,4930,3550
10,Single Bias Incidents,7103,8302,8552,6268

In [8]:
# export the edited dataframe

race.to_csv('race.csv', index=False)